# Default values for todos components
# -------------------------------------------------------------------------------------------------
# Istio Gateway variables
# -------------------------------------------------------------------------------------------------
istio:
  enabled: true
  gateway:
    enabled: true
    name: todos-gateway
    hosts:
      - "*"
    TLS:
      enabled: true
      mode: SIMPLE
      credentialName: todos-tls
# Default values for todos components
todos:
  imagePullSecrets: []
  webui:
    name: todos-webui
    route:
      enabled: false
    serviceAccount:
      annotations: { }
      name: todos-sa
    replicaCount: 1
    podAnnotations:
      sidecar.istio.io/inject: "true"
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    services:
      internal:
        enabled: true
        name: http
        protocol: TCP
        type: ClusterIP
        port: 8080
        targetPort: 8080
      external:
        enabled: false
        name: http
        protocol: TCP
        type: LoadBalancer
        port: 8080
        targetPort: 8080
    image:
      repository: quay.io/corbsmartin/todos-webui
      tag: 1.0.0
      pullPolicy: Always
    username: "Sponge Bob"
    placeholder: "Make 1000 crabby patties"
    livenessPath: "/actuator/health/liveness"
    readinessPath: "/actuator/health/readiness"