# Default values for todos components
todos:
  imagePullSecrets: []
  serviceAccount:
    annotations: { }
    name: todos-sa
  webui:
    name: todos-webui
    replicaCount: 1
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    service:
      type: LoadBalancer
      port: 8080
    image:
      repository: quay.io/corbsmartin/todos-webui
      tag: 1.0.0
      pullPolicy: Always
    username: "Sponge Bob"
    placeholder: "Make 1000 crabby patties"
    livenessPath: "/actuator/health/liveness"
    readinessPath: "/actuator/health/readiness"