{{ if not .Values.istio.enabled }}
{{ if and .Values.todos.webui.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "todos.webui.name" . }}
  labels:
    {{- include "todos.webui.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "todos.webui.name" . }}
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
{{ end }}
{{ end }}