apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "todos.mysql.name" . }}
  labels:
  {{- include "todos.mysql.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "todos.mysql.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
  gateways:
    - todos-gateway
  http:
    - match:
        - uri:
            prefix: /todos
      route:
        - destination:
            host: {{ include "todos.mysql.name" . }}
            port:
              number: {{ .Values.todos.mysql.services.internal.port }}