{{ if and .Values.istio.enabled .Values.istio.gateway.enabled }}
{{ if not .Values.istio.gateway.TLS.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      {{ toYaml .Values.istio.gateway.hosts }}
{{ end }}
{{ end }}