apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todos.mysql.name" . }}
  labels:
  {{- include "todos.mysql.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: mysql
  MYSQL_DATABASE: todos
  MYSQL_HOST: todos-db
