apiVersion: v1
kind: Service
metadata:
  name: todos-db
  labels:
    app.kubernetes.io/name: todos-db
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: todos-db
    app.kubernetes.io/component: backend