apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-db
  labels:
    app.kubernetes.io/name: todos-db
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todos-db
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todos-db
        app.kubernetes.io/component: backend
    spec:
      imagePullSecrets:
        - name: 15732902-corbett-reg-sa-pull-secret
      containers:
        - name: todos-db
          args:
            - run-mysqld
          env:
            - name: MYSQL_PASSWORD
              value: mysql123
            - name: MYSQL_DATABASE
              value: todos
            - name: MYSQL_ROOT_PASSWORD
              value: mysql123
            - name: MYSQL_USER
              value: user1
          image: registry.redhat.io/rhel8/mysql-80:latest
          ports:
            - containerPort: 3306
              hostPort: 3306
          securityContext:
            capabilities:
              drop:
                - CAP_MKNOD
                - CAP_NET_RAW
                - CAP_AUDIT_WRITE