apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "todos.webui.serviceAccountName" . }}
  labels:
    {{- include "todos.webui.labels" . | nindent 4 }}
  {{- with .Values.todos.webui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
