apiVersion: v1
kind: Service
metadata:
  name: {{ include "todos.webui.name" . }}
  labels:
    {{- include "todos.webui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.todos.webui.services.external.type }}
  ports:
    - name: {{ .Values.todos.webui.services.external.name }}
      protocol: {{ .Values.todos.webui.services.external.protocol }}
      targetPort: {{ .Values.todos.webui.services.external.targetPort }}
      port: {{ .Values.todos.webui.services.external.port }}
  selector:
    {{- include "todos.webui.selectorLabels" . | nindent 4 }}