apiVersion: v1
kind: Service
metadata:
  name: {{ include "todos.webui.name" . }}
  labels:
    {{- include "todos.webui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.todos.webui.service.type }}
  ports:
    - port: {{ .Values.todos.webui.service.port }}
      targetPort: {{ .Values.todos.webui.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "todos.webui.selectorLabels" . | nindent 4 }}